### PR TITLE
logo kicad footprint

### PR DESCRIPTION
**Pull request by sabas1080**
@jamesadevine 

Kicad footprints

;)

### CODE REVIEW

**Comment by jamesadevine** [comment]
Awesome thank you, would you be able to upload the bmp so I can generate eagle files as well?


James.

Sorry for typos and brevity, I’m typing this on a phone

On 13 Mar 2019, at 09:23, Sabas <notifications@github.com<mailto:notifications@github.com>> wrote:


@jamesadevine<https://github.com/jamesadevine>

Kicad footprints

;)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/jacdac/jacdac/pull/11

Commit Summary

  *   logo kicad footprint

File Changes

  *   A images/jacdac_logo.kicad_mod<https://github.com/jacdac/jacdac/pull/11/files#diff-0> (103)
  *   A images/jacdac_logo_14x6.kicad_mod<https://github.com/jacdac/jacdac/pull/11/files#diff-1> (103)

Patch Links:

  *   https://github.com/jacdac/jacdac/pull/11.patch
  *   https://github.com/jacdac/jacdac/pull/11.diff

**Comment by sabas1080** [comment]
@sabas1080 added logo for footprint

**Comment by jamesadevine** [comment]
@sabas1080 Oh, you can generate silk from png in KICad?

**Comment by jamesadevine** [comment]
Thanks so much @sabas1080

**Pull request merged**
